version: '3.11'

services:
  app:
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    ports:
      - '8000:8000'
    restart: always
